name: Backend CI
on: [push]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip backend
      run: zip -r backend.zip backend
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Jshint
      run: |
        sudo chmod 777 ../node_modules/.bin/jshint
        ../node_modules/.bin/jshint app.js
      working-directory: backend/src
